AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  # SharedLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     CompatibleRuntimes:
  #       - python3.8
  #     ContentUri: sample
  #     Description: Provides the base backend shared library and dependencies
  #     LayerName: shared-layer

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: handler.lambda_handler
      Runtime: python3.8
      # Layers:
      #   - !Ref SharedLayer
      # Events:
      #   HelloWorld:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /hello
      #       Method: get